# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import gcm.api


class Migration(migrations.Migration):

    dependencies = [
        ('gcm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCMMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='Topic')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('message', models.TextField(verbose_name='Message')),
                ('response', models.CharField(max_length=255, verbose_name='Response')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('NONE', 'None')], default='NONE', max_length=16, verbose_name='Status')),
                ('devices', models.ManyToManyField(to='gcm.Device')),
            ],
            bases=(gcm.api.GCMMessage, models.Model),
        ),
    ]
