# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcm', '0002_gcmmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcmmessage',
            name='topic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Topic'),
        ),
    ]
